name: Build cumulus-client
on:
  push:
    branches:
      - main
      - 'develop/**'
      - 'devops/**'
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: jdk
      - name: build and test
        id: thebuild
        run: ./gradlew build --info --init-script init.gradle
